### ISSUE TITLE
Available Meshes in the Playground

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#1074]
In the same way of [Available Textures in the Playground](http://doc.babylonjs.com/resources/playground_textures), I think we should have a page about available meshes: 

- those from [Babylon.js\Playground\scenes](https://github.com/BabylonJS/Babylon.js/tree/master/Playground/scenes)
- those from [MeshesLibrary](https://github.com/BabylonJS/MeshesLibrary)
- and conditions to be able to import custom meshes in the playground from anywhere from the Internet (with some example cases like from github, etc)

**Comment by deltakosh** [comment]
Good idea:)

**Comment by Vinc3r** [comment]
some ideas about infos in the meshes table:

- thumbnail
- size in MB
- link of an empty playground with just this mesh, a dir light and an orbit cam

If someone want to create the first basic commit of this page, let's go :) If not I will try to (dealing with this _static.json_ file I guess), but maybe not immediatly.

**Comment by BabylonJSGuide** [comment]
Have constructed a page on this and made a start, including statics. 
Have made all images 128 x 128 for consistency.
Have used the same template for all playgrounds but each mesh has a new playground so that the title and tags can include the individual name of the mesh.

Happy for you to add more and/or make any edits you wish. I will continue as and when I have time.

Question for @deltakosh  when it comes to the meshes in the MeshesLibrary which is better

A) reference them directly in the MeshesLibrary
B) copy the files into playground/scenes 

I think B but will leave the choice to DK.

**Comment by deltakosh** [comment]
Actually A because the meshes library can be access from https://models.babylonjs.com which is under a cdn
 (like https://models.babylonjs.com/ufo.glb)

**Comment by BabylonJSGuide** [comment]
Always follow the plan of those with most knowledge. Will do A

**Comment by BabylonJSGuide** [comment]
@Vinc3r have completed the page except for 
' * and conditions to be able to import custom meshes in the playground from anywhere from the Internet (with some example cases like from github, etc) '

Perhaps you could add anything you think necessary for this.

**Comment by Vinc3r** [comment]
Great job!

About "conditions etc", forget it for now (I have an internet issue at home so can't be on this subject these days). I was just thinking about:
- what append if we're on a https page and import through a http link (maybe it's not a problem)
- how do you find raw link on github to be able to import your github mesh

So that's not a big deal and can be added later.

**Comment by Vinc3r** [comment]
I think we could close this issue now, isn't it?
