### ISSUE TITLE
Create a doc for the createDefaultEnvironment helper

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#1101]
So far it lives here: http://doc.babylonjs.com/babylon101/environment#skybox (in skybox and ground chapter)
But I think he deserves more love :)

**Comment by deltakosh** [comment]
@BabylonJSGuide Please let me know if you can handle it

**Comment by BabylonJSGuide** [comment]
Give me a week to see if I can come up with something. Currently thinking that all the createDefault.... methods need more love :)

**Comment by deltakosh** [comment]
Can't agree more

**Comment by BabylonJSGuide** [comment]
First thoughts are a page under How To called Build a World Fast under scenes as a level 1 so it is near the top of the How To Landing Page.  Page would also include importing ready made models with delayCreateScene using the scene helpers. What do you think?

**Comment by deltakosh** [comment]
lovely!

**Comment by BabylonJSGuide** [comment]
Two things I need help with in writing this page. 
1).
In the current docs it says that using createDefaultEnvironment  sets createSkybox to true and createGround to true and uses CDN from Babylon. 

The same is is stated in the API and as far as I can see in the code. The following [PG](https://www.babylonjs-playground.com/#17LHMG#2) shows neither a skybox nor a ground, however both exist since using the inspector they are listed. Apply a boundingbox to them you can see their existence. So what do I need to change in order to see them?

2).
In the same PG I found that I can find the camera and light used by the arrays in scene. When I want to change any properties of the camera or light is using scene.cameras[0] and scene.lights[0] the best way of accessing them?

**Comment by deltakosh** [comment]
Pinging @sebavan for 1
For 2 the created light and camera should always be the last on the scene.cameras and scene.lights array

**Comment by sebavan** [comment]
About 1, you are seeing them, they are just really subtle and help giving a grounding feeling to the objects.

to see it better, zoom out and look a bit from the top:
![image](https://user-images.githubusercontent.com/16655165/42128515-25ebdf46-7c62-11e8-9855-2b6da3b965f1.png)

**Comment by BabylonJSGuide** [comment]
Understand it is just that I am not that good with subtle.

**Comment by BabylonJSGuide** [comment]
Done and Merged
