### ISSUE TITLE
Some pages link to http sites causing page to be marked as not secure

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/OldDocumentationSite#1314]
Example: https://doc.babylonjs.com/how_to/how_to_use_curve3

**Comment by BabylonJSGuide** [comment]
Agree that some links on that page are http not https however on click they re-direct to https. Should be easy enough to clean up though.

**Comment by BabylonJSGuide** [comment]
OK on second thoughts not quite so easy.  1192 such links. On a quick check most seem to re-direct to https sites but one or two do not. I was hoping for a quick search and replace of all but will have to be a little more careful.

**Comment by BabylonJSGuide** [comment]
Have changed all links that re-direct to https to https. That leaves 519 http links that do not re-direct to https, including www.html5gamedevs.com. Currently I have stashed the changes on the basis that the ones that can re-direct to https anyway and those that cannot would be difficult to work through and create alternatives. For many this would not even be possible. I will let @deltakosh  decide how import this issue is before continuing.

**Comment by deltakosh** [comment]
For the sake of it I would recommend merging the ones that support https.
We will leave the other unchanged as there is no other option
