### ISSUE TITLE
Regarding Playground Example re-set rotationQuaternion 

### ISSUE THREAD

**Issue by jjkavalam** [BabylonJS/OldDocumentationSite#1519]
Hi am new to the world of 3D graphics as well as to Babylon.js.

I read in:
https://doc.babylonjs.com/resources/rotation_conventions

the following:
> You cannot use both a rotation and a rotationQuaternion on a mesh. When a rotationQuaternion is applied to a mesh this overwrites the current and subsequent use of rotation producing the wrong orientation. Should you want to use rotation after a rotationQuaternion has been applied, for example on an imported mesh, then the rotationQuaternion has to be set to null.
> To see this effect comment out line 48 in the following playground
>
> Playground Example re-set rotationQuaternion (https://www.babylonjs-playground.com/#1ST43U#77)

In my understanding by commenting out line 48 (which set the rotationQuaternion to null) it is expected that the two boxes will not be aligned anymore. But the example doesn't seem to do that.

Something seems amiss with my understanding / the example ?

**Comment by deltakosh** [comment]
Hello do you mind asking the question on our forum? forum.babylonjs,.com

Thanks a lot!

**Comment by jjkavalam** [comment]
@deltakosh Thank you for taking the time to respond. I have submitted the question in the forum.

**Comment by BabylonJSGuide** [comment]
@jjkavalaam, @deltakosh I could not find the question on the forum. The warning was included because there were many questions in the old forum on rotation problems after importing a mesh that already had a rotation quaternion set. 

http://www.html5gamedevs.com/topic/41045-trying-to-animate-a-girl-to-rotation-90-degree-result-in-her-rotate-in-circles-with-pg/?do=findComment&comment=233867

The issue on not being able to set rotation after rotationQuaternion was set was occuring in V3 and now seems not to be the case with V4 so something must have changed in the core code.

Will mark the warning as pre version 4 once it is confirmed that whatever changed will mean you can now change the value of rotation successfully after rotationQuaternion has been set in all circumstances.

**Comment by deltakosh** [comment]
Yeah this is right, now setting the rotation will just add it to the quaternion if the latter was already set
