### ISSUE TITLE
Reconsider "Table of Contents" as name for lesson sections

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1863]
I think of "Table of Contents" as the overall list of "chapters" in a book or lessons in a course. I expected an up arrow next to those words to take me to https://doc.babylonjs.com/babylon101/. 

A name like "Lesson Topics" would be more intuitive.

**Comment by PirateJC** [comment]
@jgfoster - I'm closing this issue because it's being wrapped into this other issue:

https://github.com/babylonjs/documentation/issues/1842

We are actively reorganizing the documentation and our top priority/focus is to restructure from a "choose your own adventure" type organization to a "chapter book" approach ;)  So closing this issue as it's a duplicate, but please know that this is of HIGH importance and is being done!
