### ISSUE TITLE
Update CSS

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#557]
As we can see in [blender doc](http://doc.babylonjs.com/exporters/blender#world), some html elements haven't css assigned:

- h4
- th
- th a

![css](http://i.imgur.com/oz5r9JG.png)

suggestion, use for now same css as h3:
```css
font-weight: 300;
font-family: "Open Sans";
```

**Comment by deltakosh** [comment]
Do you mind creating a PR?

**Comment by Vinc3r** [comment]
No problem, I will do that asap

**Comment by Vinc3r** [comment]
Do I have to edit main.css in [website/scss folder ](https://github.com/BabylonJS/Website/blob/master/scss/main.css)or [main.css in css folder](https://github.com/BabylonJS/Website/blob/master/css/main.css) ? or even[ main.scss ](https://github.com/BabylonJS/Website/blob/master/scss/main.scss)(in that case I don't know how scss works)

**Comment by deltakosh** [comment]
Ping @temechon for validation of the right procedure

**Comment by deltakosh** [comment]
So after some investigations I think it should be in scss. Working on it :)

**Comment by deltakosh** [comment]
actually I'll wait for @Temechon  :D

**Comment by deltakosh** [comment]
Upppppp ;D

**Comment by Kimoen** [comment]
Hi @Vinc3r !
Wow sorry I didn't read the notif :( Yes indeed you jave to update the scss file. It's basically the same as CSS but with a lot a features added. Simple css works correctly.
In order to test your changes, you have to recompile the main.css file with the command 'grunt sass'.

Feel free to get back to me via this issue if you have any trouble, I'll be happy to do it for you !

**Comment by Vinc3r** [comment]
Css seems to have been update since I posted this issue. I think I can close that. (great thing because I would certainly not trying to recompile some things :-D )
