### ISSUE TITLE
Improve docs for raySelectionPredicate, meshSelectionPredicate, onNewMeshSelected, onNewMeshPicked

### ISSUE THREAD

**Issue by TrevorDev** [BabylonJS/OldDocumentationSite#826]
I had implemented some picking logic using the raySelectionPredicate function and didn’t realize that the teleportation uses that too. I’m still pretty unclear on the intended difference between `raySelectionPredicate` and `meshSelectionPredicate`. Also `onNewMeshSelected` vs `onNewMeshPicked`. The documentation here is all I could find and it’s definitely not clear. 

https://doc.babylonjs.com/how_to/webvr_helper#gaze-and-interaction

**Comment by deltakosh** [comment]
Pinging @CarlosLanderas

**Comment by CarlosLanderas** [comment]
Hi @deltakosh  and @TrevorDev .
When I started developing my project I was a little bit confused too about the raySelectionPredicate and meshSelectionPredicate. Basically, both rays are used for interaction and teleportation at the same time.
The raySelection predicate composes your predicate with an internal one in VRHelper. That predicate checks if the collided mesh is a floor mesh and the configured stick is being pressed to render the teleporationTarget and trigger the teleportCamera and checkRotate methods on release. If the collided target is not a floor mesh, it executes the interaction branch, were your meshPredicate indicates what are the target meshes to interact with and avoid geometry collision checks with any other meshes. If the target mesh matches the pedicate, the gaze color will change and onNewMeshSelected observable will trigger.

Some weeks ago, I was testing the onNewMeshSelected observable to receive the mesh I was targetting and I realize that the callback was only providing me with the target mesh, and I really needed to get additional pickInfo information like the distance to make possible interacting with objects based on distance with the Camera. Raanan and I were talking about this topic, and we decided the VRHelper was young enough to change the callback from Mesh to PickInfo and I changed the signature and documented the breaking change, but then Rousseau suggested adding another observable so we do not break the public API. So basically the onNewMeshSelected / OnNewMeshPicked are the same observable events, but the seconds provides more information that might help you configuring your interactions better.

Later I added the OnSelectedMeshUnselected observable, because the default rayPredicate was all visible meshes and the default meshPredicate was () => true, so it was really expensive if you are playing with a big scene. This new observable was needed because there was not a way to know when you stopped targeting a mesh, in addition it should be raised when a previous mesh was selected but your ray is not colliding anything, so if you configure your meshRay very restricted you can get notified if no other mesh has a collision.

Sorry for the  looong text. If you need some help with documentation I would be glad to help.

Greetings
