### ISSUE TITLE
Resources: new "Playground" filter

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#944]
I think this page need a new "Playground" filter: http://doc.babylonjs.com/resources/ but I don't know how to do that, if someone can explain, or made the change?

![](https://i.imgur.com/TnK3Z6g.png)

Page which should be included in this filtering are:

- http://doc.babylonjs.com/resources/playgrounds
- http://doc.babylonjs.com/resources/pbt
- http://doc.babylonjs.com/resources/playground_textures

**Comment by deltakosh** [comment]
Pinging @babylonjsguide :)

**Comment by BabylonJSGuide** [comment]
EDIT Problem below solved by deleting node_modules and redoing node install etc
***************************************************************************************************
Have made changes but I am having problems with Grunt Build to check changes are ok. Get the following error messages after Grunt Build

$ grunt build
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'serve-static'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

Tried installing grunt-contrib-connect but get these error messages
$ npm install grunt-contrib-connect --save-dev
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
npm WARN grunt-contrib-clean@0.6.0 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-watch@0.6.1 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-express-server@0.4.19 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies
yourself.

npm ERR! Cannot read property '0' of undefined

Any help appreciated. I do not want to do a PR before checking results of the changes I made locally.

**Comment by BabylonJSGuide** [comment]
A good idea and PR #945 submitted. @Vinc3r you should be able to see how it was done by looking at the file changes. Basically a new folder in content>resources and moving files to this new folder plus updating data>statics.json. Since all changes take place withing the resources folder no need to change any existing links to these pages.

**Comment by Vinc3r** [comment]
Great job, thanks
